# Generated by Django 5.0.6 on 2024-06-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem2app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinflip',
            old_name='flip_time',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='coinflip',
            name='result',
            field=models.CharField(choices=[('heads', 'Орёл'), ('tails', 'Решка')], max_length=5),
        ),
    ]
