# Generated by Django 5.0.6 on 2024-06-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sem2app1', '0004_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Author',
        ),
    ]
