# Generated by Django 5.0.6 on 2024-06-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem4app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlipCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('heads', 'Орел'), ('tails', 'Решка')], max_length=5)),
                ('flip_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
